# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

import octoflatbuffers
from typing import Any
from homeway.Proto.SageAudioDataContext import SageAudioDataContext
from typing import Optional
class SageStream(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = octoflatbuffers.encode.Get(octoflatbuffers.packer.uoffset, buf, offset)
        x = SageStream()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSageStream(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SageStream
    def Init(self, buf: bytes, pos: int):
        self._tab = octoflatbuffers.table.Table(buf, pos)

    # SageStream
    def StreamId(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SageStream
    def IsOpenMsg(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(octoflatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SageStream
    def IsDataTransmissionDone(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(octoflatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SageStream
    def IsCloseMsg(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(octoflatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SageStream
    def Type(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SageStream
    def AudioContext(self) -> Optional[SageAudioDataContext]:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SageAudioDataContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SageStream
    def AudioData(self, j: int):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, a + octoflatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SageStream
    def AudioDataAsNumpy(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(octoflatbuffers.number_types.Int8Flags, o)
        return 0

    # SageStream
    def AudioDataAsByteArray(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsByteArray(o)
        return 0

    # SageStream
    def AudioDataLength(self) -> int:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SageStream
    def AudioDataIsNone(self) -> bool:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # SageStream
    def Text(self) -> Optional[str]:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SageStreamStart(builder: octoflatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: octoflatbuffers.Builder):
    SageStreamStart(builder)

def SageStreamAddStreamId(builder: octoflatbuffers.Builder, streamId: int):
    builder.PrependUint32Slot(0, streamId, 0)

def AddStreamId(builder: octoflatbuffers.Builder, streamId: int):
    SageStreamAddStreamId(builder, streamId)

def SageStreamAddIsOpenMsg(builder: octoflatbuffers.Builder, isOpenMsg: bool):
    builder.PrependBoolSlot(1, isOpenMsg, 0)

def AddIsOpenMsg(builder: octoflatbuffers.Builder, isOpenMsg: bool):
    SageStreamAddIsOpenMsg(builder, isOpenMsg)

def SageStreamAddIsDataTransmissionDone(builder: octoflatbuffers.Builder, isDataTransmissionDone: bool):
    builder.PrependBoolSlot(2, isDataTransmissionDone, 0)

def AddIsDataTransmissionDone(builder: octoflatbuffers.Builder, isDataTransmissionDone: bool):
    SageStreamAddIsDataTransmissionDone(builder, isDataTransmissionDone)

def SageStreamAddIsCloseMsg(builder: octoflatbuffers.Builder, isCloseMsg: bool):
    builder.PrependBoolSlot(3, isCloseMsg, 0)

def AddIsCloseMsg(builder: octoflatbuffers.Builder, isCloseMsg: bool):
    SageStreamAddIsCloseMsg(builder, isCloseMsg)

def SageStreamAddType(builder: octoflatbuffers.Builder, type: int):
    builder.PrependInt8Slot(4, type, 0)

def AddType(builder: octoflatbuffers.Builder, type: int):
    SageStreamAddType(builder, type)

def SageStreamAddAudioContext(builder: octoflatbuffers.Builder, audioContext: int):
    builder.PrependUOffsetTRelativeSlot(5, octoflatbuffers.number_types.UOffsetTFlags.py_type(audioContext), 0)

def AddAudioContext(builder: octoflatbuffers.Builder, audioContext: int):
    SageStreamAddAudioContext(builder, audioContext)

def SageStreamAddAudioData(builder: octoflatbuffers.Builder, audioData: int):
    builder.PrependUOffsetTRelativeSlot(6, octoflatbuffers.number_types.UOffsetTFlags.py_type(audioData), 0)

def AddAudioData(builder: octoflatbuffers.Builder, audioData: int):
    SageStreamAddAudioData(builder, audioData)

def SageStreamStartAudioDataVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartAudioDataVector(builder, numElems: int) -> int:
    return SageStreamStartAudioDataVector(builder, numElems)

def SageStreamAddText(builder: octoflatbuffers.Builder, text: int):
    builder.PrependUOffsetTRelativeSlot(7, octoflatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def AddText(builder: octoflatbuffers.Builder, text: int):
    SageStreamAddText(builder, text)

def SageStreamEnd(builder: octoflatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: octoflatbuffers.Builder) -> int:
    return SageStreamEnd(builder)
