# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Proto

import octoflatbuffers
from typing import Any
from typing import Optional
class SageDataContext(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = octoflatbuffers.encode.Get(octoflatbuffers.packer.uoffset, buf, offset)
        x = SageDataContext()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSageDataContext(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SageDataContext
    def Init(self, buf: bytes, pos: int):
        self._tab = octoflatbuffers.table.Table(buf, pos)

    # SageDataContext
    def DataType(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SageDataContext
    def SampleRate(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SageDataContext
    def Channels(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SageDataContext
    def BytesPerSample(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(octoflatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SageDataContext
    def LanguageCode(self) -> Optional[str]:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SageDataContext
    def HomeContext(self, j: int):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(octoflatbuffers.number_types.Uint8Flags, a + octoflatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SageDataContext
    def HomeContextAsNumpy(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(octoflatbuffers.number_types.Uint8Flags, o)
        return 0

    # SageDataContext
    def HomeContextAsByteArray(self):
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsByteArray(o)
        return 0

    # SageDataContext
    def HomeContextLength(self) -> int:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SageDataContext
    def HomeContextIsNone(self) -> bool:
        o = octoflatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def SageDataContextStart(builder: octoflatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: octoflatbuffers.Builder):
    SageDataContextStart(builder)

def SageDataContextAddDataType(builder: octoflatbuffers.Builder, dataType: int):
    builder.PrependInt8Slot(0, dataType, 0)

def AddDataType(builder: octoflatbuffers.Builder, dataType: int):
    SageDataContextAddDataType(builder, dataType)

def SageDataContextAddSampleRate(builder: octoflatbuffers.Builder, sampleRate: int):
    builder.PrependUint32Slot(1, sampleRate, 0)

def AddSampleRate(builder: octoflatbuffers.Builder, sampleRate: int):
    SageDataContextAddSampleRate(builder, sampleRate)

def SageDataContextAddChannels(builder: octoflatbuffers.Builder, channels: int):
    builder.PrependInt8Slot(2, channels, 0)

def AddChannels(builder: octoflatbuffers.Builder, channels: int):
    SageDataContextAddChannels(builder, channels)

def SageDataContextAddBytesPerSample(builder: octoflatbuffers.Builder, bytesPerSample: int):
    builder.PrependInt8Slot(3, bytesPerSample, 0)

def AddBytesPerSample(builder: octoflatbuffers.Builder, bytesPerSample: int):
    SageDataContextAddBytesPerSample(builder, bytesPerSample)

def SageDataContextAddLanguageCode(builder: octoflatbuffers.Builder, languageCode: int):
    builder.PrependUOffsetTRelativeSlot(4, octoflatbuffers.number_types.UOffsetTFlags.py_type(languageCode), 0)

def AddLanguageCode(builder: octoflatbuffers.Builder, languageCode: int):
    SageDataContextAddLanguageCode(builder, languageCode)

def SageDataContextAddHomeContext(builder: octoflatbuffers.Builder, homeContext: int):
    builder.PrependUOffsetTRelativeSlot(5, octoflatbuffers.number_types.UOffsetTFlags.py_type(homeContext), 0)

def AddHomeContext(builder: octoflatbuffers.Builder, homeContext: int):
    SageDataContextAddHomeContext(builder, homeContext)

def SageDataContextStartHomeContextVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartHomeContextVector(builder, numElems: int) -> int:
    return SageDataContextStartHomeContextVector(builder, numElems)

def SageDataContextEnd(builder: octoflatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: octoflatbuffers.Builder) -> int:
    return SageDataContextEnd(builder)
